module.exports = {
  CONVERSATIONS: {
    GET_CONVERSATION: 'GET_CONVERSATION',
    GET_CONVERSATION_SUCCESS: 'GET_CONVERSATION_SUCCESS',
    GET_CONVERSATION_FAILED: 'GET_CONVERSATION_FAILED',
    GET_CONVERSATION_BY_ID: 'GET_CONVERSATION_BY_ID',
    GET_CONVERSATION_BY_ID_SUCCESS: 'GET_CONVERSATION_BY_ID_SUCCESS',
    GET_CONVERSATION_BY_ID_FAILED: 'GET_CONVERSATION_BY_ID_FAILED',
  },
  USERS: {
    GET_ME: 'GET_ME',
    GET_ME_SUCCESS: 'GET_ME_SUCCESS',
    GET_ME_FAILED: 'GET_ME_FAILED',
  },
};
